# graph 名称
name: "CalculatorService"

# graph 详细描述
description: "科学计算智能体可以接收计算任务，并使用python计算结果返回"

# 为了完成任务的计划，通过调用 group 完成任务
groups:
  - CalculatorGroup

# 任务执行过程中的上下文信息（如返回值等），用于 group 之间的信息传递
context:
  - name: "task"
    type: "str"
  - name: "result"
    type: "str"
